# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-14 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_comments'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='comment',
            index_together=set([('article',)]),
        ),
    ]
